# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements-test.txt
RUN pip install --no-cache-dir -r requirements-test.txt

# Run script or command to start your tests
CMD ["python", "test_orders_analysis.py"]
